"""mw table

Revision ID: 8197ddad516d
Revises: 
Create Date: 2021-08-13 12:35:44.643943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8197ddad516d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musical_workDB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('artist', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('melody', sa.String(length=120), nullable=True),
    sa.Column('key', sa.String(length=3), nullable=True),
    sa.Column('searchCount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_musical_workDB_melody'), 'musical_workDB', ['melody'], unique=True)
    op.create_index(op.f('ix_musical_workDB_title'), 'musical_workDB', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_musical_workDB_title'), table_name='musical_workDB')
    op.drop_index(op.f('ix_musical_workDB_melody'), table_name='musical_workDB')
    op.drop_table('musical_workDB')
    # ### end Alembic commands ###
